# Generated by Django 4.1.7 on 2023-03-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_profile_education'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
