# Generated by Django 4.1.7 on 2023-03-05 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_ob_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='ob_type',
            new_name='Job_type',
        ),
    ]
