# Generated by Django 4.1.7 on 2023-03-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_job_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company_logo',
        ),
    ]
